name: Cilium Integration Tests
on:
  push:
    branches:
      - master
  pull_request: {}
  issue_comment:
    types:
      - created
env:
  KIND_VERSION: v0.18.0
  CILIUM_REPO_REF: master
  CILIUM_CLI_TAG: latest

jobs:
  cilium-connectivity-tests:
    timeout-minutes: 360
    name: Cilium Connectivity Tests
    runs-on: ubuntu-latest
    steps:
      - name: Prepare variables for pushing to master
        if: github.event_name == 'push'
        run: |
          echo "PROXY_IMAGE=quay.io/cilium/cilium-envoy" >> $GITHUB_ENV
          echo "PROXY_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Prepare variables for PR
        if: github.event_name == 'pull_request'
        run: |
          echo "PROXY_IMAGE=quay.io/cilium/cilium-envoy-dev" >> $GITHUB_ENV
          echo "PROXY_TAG=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      - name: Prepare variables for issue comment on a PR
        if: github.event_name == 'issue_comment' && github.event.issue.pull_request && startsWith(github.event.comment.body, '/cilium-integration-test')
        run: |
          echo "PROXY_IMAGE=quay.io/cilium/cilium-envoy-dev" >> $GITHUB_ENV
          echo "PROXY_TAG=${{ github.event.issue.pull_request.head.sha }}" >> $GITHUB_ENV

          commentBody="${{ github.event.comment.body }}"

          ciliumRef=${CILIUM_REPO_REF}
          if [[ "$commentBody" == *" cilium="* ]]; then
            ciliumRef=$(echo "$commentBody" | sed -E 's|.* cilium=([^ ]*).*|\1|g')
          fi
          echo "CILIUM_REPO_REF=${ciliumRef}" >> $GITHUB_ENV

          ciliumCliTag=${CILIUM_CLI_TAG}
          if [[ "${{ github.event.comment.body }}" == *" ciliumCli="* ]]; then
            ciliumCliTag=$(echo "$commentBody" | sed -E 's|.* ciliumCli=([^ ]*).*|\1|g')
          fi
          echo "CILIUM_CLI_TAG=${ciliumCliTag}" >> $GITHUB_ENV

      - uses: actions/github-script@v6
        if: github.event_name == 'issue_comment' && github.event.issue.pull_request && startsWith(github.event.comment.body, '/cilium-integration-test')
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.issue.number }},
              body: "👋 https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}"
            })

      - name: Checkout Cilium ${{ env.CILIUM_REPO_REF }}
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          repository: cilium/cilium # Be aware that this is the Cilium repository and not the one of the proxy itself!
          ref: ${{ env.CILIUM_REPO_REF }}

      - name: Install Cilium CLI ${{ env.CILIUM_CLI_TAG }}
        run: |
          cid=$(docker create quay.io/cilium/cilium-cli-ci:${{ env.CILIUM_CLI_TAG }} ls)
          sudo docker cp $cid:/usr/local/bin/cilium /usr/local/bin
          docker rm $cid
          cilium version

